# PDV Ibix — constantes logística entregador (pagamento à praça)
STATUS_PAGAMENTO_ENTREGADOR_PENDENTE = "pendente"
STATUS_PAGAMENTO_ENTREGADOR_LIBERADO = "liberado"
STATUS_PAGAMENTO_ENTREGADOR_PAGO = "pago"

STATUS_PAGAMENTO_ENTREGADOR_VALUES = frozenset(
    {
        STATUS_PAGAMENTO_ENTREGADOR_PENDENTE,
        STATUS_PAGAMENTO_ENTREGADOR_LIBERADO,
        STATUS_PAGAMENTO_ENTREGADOR_PAGO,
    }
)
