# PDV Ibix - Códigos de erro padronizados para API mobile
# Retornados no body JSON: {"detail": "<mensagem>", "code": "<CONSTANTE>"}

# Auth
AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
AUTH_REFRESH_TOKEN_INVALID = "AUTH_REFRESH_INVALID"
AUTH_REFRESH_TOKEN_EXPIRED = "AUTH_REFRESH_EXPIRED"
AUTH_SOCIAL_EMAIL_CONFLICT = "AUTH_SOCIAL_EMAIL_CONFLICT"
AUTH_APPLE_VERIFICATION_FAILED = "AUTH_APPLE_VERIFY_FAILED"

# Consumidor
CONSUMIDOR_NAO_ENCONTRADO = "CONSUMIDOR_NOT_FOUND"
CONSUMIDOR_INATIVO = "CONSUMIDOR_INACTIVE"
CONSUMIDOR_DELETADO = "CONSUMIDOR_DELETED"

# Anúncio
ANUNCIO_NAO_ENCONTRADO = "ANUNCIO_NOT_FOUND"
ANUNCIO_INDISPONIVEL = "ANUNCIO_UNAVAILABLE"
ANUNCIO_SEM_ESTOQUE = "ANUNCIO_OUT_OF_STOCK"

# Favorito
FAVORITO_JA_EXISTE = "FAVORITO_ALREADY_EXISTS"
FAVORITO_NAO_ENCONTRADO = "FAVORITO_NOT_FOUND"

# Notificação
NOTIFICACAO_NAO_ENCONTRADA = "NOTIFICACAO_NOT_FOUND"

# Push
PUSH_TOKEN_INVALIDO = "PUSH_TOKEN_INVALID"
PUSH_TOKEN_JA_REGISTRADO = "PUSH_TOKEN_ALREADY_REGISTERED"
PUSH_TOKEN_NAO_ENCONTRADO = "PUSH_TOKEN_NOT_FOUND"

# Cupom (Sprint 2)
CUPOM_INVALIDO = "COUPON_INVALID"
CUPOM_EXPIRADO = "COUPON_EXPIRED"
CUPOM_LIMITE_ATINGIDO = "COUPON_LIMIT_REACHED"
CUPOM_VALOR_MINIMO = "COUPON_MIN_VALUE_NOT_MET"

# Devolução / Cancelamento (Sprint 2)
DEVOLUCAO_PRAZO_EXPIRADO = "RETURN_PERIOD_EXPIRED"
DEVOLUCAO_STATUS_INVALIDO = "RETURN_INVALID_STATUS"
DEVOLUCAO_JA_ABERTA = "RETURN_ALREADY_OPEN"
PEDIDO_NAO_ENCONTRADO = "PEDIDO_NOT_FOUND"
PEDIDO_NAO_CANCELAVEL = "ORDER_NOT_CANCELLABLE"
PEDIDO_NAO_RETORNAVEL = "ORDER_NOT_RETURNABLE"

# Upload
UPLOAD_TIPO_INVALIDO = "UPLOAD_INVALID_TYPE"
UPLOAD_TAMANHO_EXCEDIDO = "UPLOAD_SIZE_EXCEEDED"

# App versão
APP_VERSAO_NAO_ENCONTRADA = "APP_VERSION_NOT_FOUND"

# Chat
LOJA_NAO_ENCONTRADA = "LOJA_NOT_FOUND"
CONVERSA_NAO_ENCONTRADA = "CONVERSA_NOT_FOUND"
CONVERSA_NAO_PERTENCE = "CONVERSA_NOT_OWNED"
MENSAGEM_VAZIA = "MESSAGE_EMPTY"

# LGPD
CONSENTIMENTO_TIPO_INVALIDO = "CONSENT_INVALID_TYPE"
SENHA_INCORRETA = "WRONG_PASSWORD"

# Geral
RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
VALIDATION_ERROR = "VALIDATION_ERROR"
INTERNAL_ERROR = "INTERNAL_ERROR"
